### ISSUE TITLE
The CI failed when I fetch this repo

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/content#18412]
`PR review companion workflow run failed for main branch`

The stack trace:
```
Run PR_NUMBER=`cat build/NR`
Pull request:
https://github.com/mdn/content/pull/
Deployer (0.3.0)
Upload files from: /home/runner/work/content/content/build
Upload into: pr/ of mdn-content-dev
Total pending file uploads: 1,072 ([39](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:40).9ms)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1[40](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:41)4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/main.py", line 200, in upload
    upload_content(directory, content_roots, ctx.obj)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/upload.py", line 549, in upload_content
    existing_bucket_objects = mgr.get_bucket_objects()
  File "/home/runner/work/content/content/yari/deployer/src/deployer/upload.py", line 352, in get_bucket_objects
    response = self.client.list_objects_v2(**kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 898, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line [41](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:42)2, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 2[56](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:57), in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/signers.py", line 103, in handler
    return self.sign(operation_name, request)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/signers.py", line 1[87](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:88), in sign
    auth.add_auth(request)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/auth.py", line 407, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
Total existing S3 objects: 
Error: Process completed with exit code 1.
```

**Comment by yin1999** [comment]
[AWS S3 credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#environment-variables) are required for this workflow
