### ISSUE TITLE
Broken syntax macro

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#18815]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-style

### What specific section or headline is this issue about?

Formal syntax

### What information was incorrect, unhelpful, or incomplete?

<img width="120" alt="image" src="https://user-images.githubusercontent.com/9212605/181023704-f95ecd3b-8930-4eef-b11f-263e94fb18e8.png">

I can see the raw macro.

### What did you expect to see?

CSS syntax definition.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-style/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for raising this and investigating and finding the https://github.com/csstree/csstree/issues/192 connection

For the record here, pasting in the stack trace:

```
SyntaxError: Expect `,`
    at Tokenizer.error (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/tokenizer.cjs:52:15)
    at Tokenizer.eat (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/tokenizer.cjs:43:18)
    at readTypeRange (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/parse.cjs:252:15)
    at readType (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/parse.cjs:298:16)
    at peek (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/parse.cjs:467:19)
    at readImplicitGroup (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/parse.cjs:393:20)
    at Object.parse (/Users/mike/workspace/mdn/yari/node_modules/css-tree/cjs/definition-syntax/parse.cjs:547:20)
    at renderSyntax ("/Users/mike/workspace/mdn/yari/kumascript/macros/CSSSyntax.ejs":249:32)
```

And the syntax statement it’s attempting to parse is:

https://drafts.csswg.org/css-fonts/#font-style-prop
> ```
> normal | italic | oblique <angle [−90deg,90deg]>?
> ```

And `<angle [−90deg,90deg]>` is specifically mentioned in https://github.com/csstree/csstree/issues/192 as an example that breaks the parser.

There may be some way we could work around it in the meantime while we’re waiting for that bug to get fixed upstream, but it doesn’t seem at all clear how we might try to do that. Anyway, transferring this to the Yari repo to get more eyes on it.
