### ISSUE TITLE
api.CSSStyleDeclaration.setProperty - <Buttons in provided example doesn't work>

### ISSUE THREAD

**Issue by Omid-Heidarzadeh** [mdn/content#19312]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Three buttons in the example are supposed to change text color, background color, and border attributes of a sample box to random values. Clicking on each of which, on the latest versions of chrome, firefox, and edge throws this error:

"**Uncaught TypeError: Cannot read properties of undefined (reading 'style') at HTMLButtonElement.setRandomBorder (_sample_.examples.html:130:15)**"

But it works as intended on Opera GX LVL 4 (core: 89.0.4447.64). 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox

### Did you test this? If so, how?

I tested it on: 
Chrome 104.0.5112.81
Firefox 103.0.1
Edge 104.0.1293.47
Opera GX LVL 4 (core: 89.0.4447.64)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.CSSStyleDeclaration.setProperty`
* Report started: 2022-08-09T04:47:18.375Z

</details>

**Comment by teoli2003** [comment]
The example works for me on:
- Chrome Version 104.0.5112.79 (Build officiel) (arm64)
- Safari Version 15.4 (17613.1.17.1.13)
- Firefox Nightly Version 105.0a1 (2022-08-02) (64 bits)

I suggest something is interfering with the page on your side.

**Comment by Omid-Heidarzadeh** [comment]
Thanks for your suggestion. It seems my antivirus has some interference with the page on specific browsers and when I disable it and refresh the page the example works.
In addition to the error mentioned above, there are 3 errors logged in the console every time the page loads, which is not the case on other MDN pages. They are as follows:

- react-dom.production.min.js:118 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qr (react-dom.production.min.js:118:466)
    at yl (react-dom.production.min.js:199:369)
    at yc (react-dom.production.min.js:280:85)
    at bc (react-dom.production.min.js:279:450)
    at vc (react-dom.production.min.js:279:320)
    at mc (react-dom.production.min.js:279:180)
    at rc (react-dom.production.min.js:267:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)
Qr @ react-dom.production.min.js:118
yl @ react-dom.production.min.js:199
yc @ react-dom.production.min.js:280
bc @ react-dom.production.min.js:279
vc @ react-dom.production.min.js:279
mc @ react-dom.production.min.js:279
rc @ react-dom.production.min.js:267
S @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14

- react-dom.production.min.js:147 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mi (react-dom.production.min.js:147:278)
    at xs (react-dom.production.min.js:292:486)
    at bc (react-dom.production.min.js:279:389)
    at vc (react-dom.production.min.js:279:320)
    at mc (react-dom.production.min.js:279:180)
    at rc (react-dom.production.min.js:267:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)
Mi @ react-dom.production.min.js:147
xs @ react-dom.production.min.js:292
bc @ react-dom.production.min.js:279
vc @ react-dom.production.min.js:279
mc @ react-dom.production.min.js:279
rc @ react-dom.production.min.js:267
S @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14

- react-dom.production.min.js:292 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xs (react-dom.production.min.js:292:155)
    at bc (react-dom.production.min.js:279:389)
    at vc (react-dom.production.min.js:279:320)
    at mc (react-dom.production.min.js:279:180)
    at ac (react-dom.production.min.js:270:88)
    at rc (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)
    
These may be irrelevant to the subject but I just wanted to let you know.
