### ISSUE TITLE
"yarn start" stopped workng after executing "yarn install"

### ISSUE THREAD

**Issue by mikecat** [mdn/content#24489]
# Environment

Windows 10 Home 21H2 x64

```
D:\MyData\Documents\mdn\content>node -v
v18.12.1

D:\MyData\Documents\mdn\content>yarn -v
1.22.19
```

# What I did

With the commit `2affc88e29596d3f58930d6f546c7f4b35a3a2ac`

I executed the command `yarn start` to launch the testing HTTP server. It worked, but some message appeared to suggest doing `yarn install`.

```
D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:11716) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
The installed version of Yari (1.33.20) is older than the version referenced in package.json (2.1.6). Please make sure your main git branch is up-to-date with https://github.com/mdn/content/, then run yarn install to install the latest Yari.
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
[HPM] Proxy created: /  -> http://localhost:8080
[HPM] Proxy created: /  -> https://developer.mozilla.org
CONTENT_ROOT: D:\MyData\Documents\mdn\content\files
Listening on port 5042
Your EDITOR is set to: C:\Program Files (x86)\sakura\sakura.exe
```

After stopping the server, I used `git pull` to update to the commit `499a147561f3b7c4878d65bd2232c7ff96803ec6`.

After that, I executed `yarn install`.

```
D:\MyData\Documents\mdn\content>yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@mdn/yari > @use-it/interval@1.0.0" has unmet peer dependency "react@>=16.8".
warning "@mdn/yari > html-react-parser@3.0.9" has unmet peer dependency "react@0.14 || 15 || 16 || 17 || 18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 63.15s.
```

Then, I executed `yarn start` to start the server again, but now it failed.

```
D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:2072) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8280) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:393:5)
    at getPathFromURLWin32 (node:internal/url:1458:11)
    at fileURLToPath (node:internal/url:1488:22)
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:789413
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:794758
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried doing `git checkout 2affc88e29` to roll back the contents version and tried `yarn` and `yarn start`, but it failed with similar error.

```
D:\MyData\Documents\mdn\content>yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 1.04s.

D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:17820) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1116) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:393:5)
    at getPathFromURLWin32 (node:internal/url:1458:11)
    at fileURLToPath (node:internal/url:1488:22)
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:789413
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:794758
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also renamed `.env` to `.env_disable` to disable my customized settings, but `yarn start` continued failing.

```
D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:8756) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18320) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:393:5)
    at getPathFromURLWin32 (node:internal/url:1458:11)
    at fileURLToPath (node:internal/url:1488:22)
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:789413
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:794758
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# Question

I have almost no knowledge about Node.js and yarn. What should I do to have the testing server work again?

**Comment by bsmth** [comment]
Hi @mikecat could you try deleting the `node_modules` folder and retrying the commands:

```bash
yarn
yarn start
```

Let us know if the problem persists.

**Comment by mikecat** [comment]
@bsmth Thank you, but it didn't work.

1. Updated to commit `44b6f00d5cab292b73d86333db9c4b5719a32e09`
2. Moved `node_modules` and `.env` to an unrelated directory
3. Executed `yarn` and `yarn start`

Result:

```
D:\MyData\Documents\mdn\content>yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@mdn/yari > @use-it/interval@1.0.0" has unmet peer dependency "react@>=16.8".
warning "@mdn/yari > html-react-parser@3.0.9" has unmet peer dependency "react@0.14 || 15 || 16 || 17 || 18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 34.96s.

D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:17140) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8396) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:393:5)
    at getPathFromURLWin32 (node:internal/url:1458:11)
    at fileURLToPath (node:internal/url:1488:22)
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:802668
    at file:///D:/MyData/Documents/mdn/content/node_modules/@mdn/yari/ssr/dist/main.js:2:808062
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikecat** [comment]
Looks working again after doing `yarn` and `yarn install` with commit `f85f713665e5d53bb05f5f49882cd8a77137584d`.

```
D:\MyData\Documents\mdn\content>yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@mdn/yari > @use-it/interval@1.0.0" has unmet peer dependency "react@>=16.8".
warning "@mdn/yari > html-react-parser@3.0.9" has unmet peer dependency "react@0.14 || 15 || 16 || 17 || 18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 48.98s.

D:\MyData\Documents\mdn\content>yarn start
yarn run v1.22.19
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:1204) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16332) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
Corrected the CONTENT_TRANSLATED_ROOT environment variable to D:\MyData\Documents\mdn\translated-content\files
[HPM] Proxy created: /  -> http://localhost:8080
[HPM] Proxy created: /  -> https://developer.mozilla.org
[HPM] Proxy created: /  -> https://developer.allizom.org
CONTENT_ROOT: D:\MyData\Documents\mdn\content\files
Listening on port 5042
Your EDITOR is set to: C:\Program Files (x86)\sakura\sakura.exe
```

**Comment by bsmth** [comment]
Thanks for the update @mikecat, glad it's working again.
