### ISSUE TITLE
Issue with "Introducing a complete toolchain": New version of Parcel does not seem to work in tooling tutorial

### ISSUE THREAD

**Issue by venven-de** [mdn/content#2862]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

#### What information was incorrect, unhelpful, or incomplete?
running parcel at the very end of the page returns an error 
Invalid Version: undefined
    at new SemVer (/home/tuven/Desktop/will-it-miss/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/home/tuven/Desktop/will-it-miss/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at lt (/home/tuven/Desktop/will-it-miss/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /home/tuven/Desktop/will-it-miss/node_modules/@babel/preset-env/lib/index.js:276:22

#### Specific section or headline?
Build and transformation tools:
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain#build_and_transformation_tools

#### What did you expect to see?
installing parcel-bundler@1.12.3 instead of the current version of parcel does the job . idk why

#### Did you test this? If so, how?
i did test parcel bundler 1.12.4 which did not work and version 1.12.3 which worked all fine

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this: You would need to investigate this carefully, running through the tutorial to see if you can reproduce the error.

@venven-de can you let us know where exactly you were in the tutorial when you got this error? Which setep, or under which heading? Thanks!

**Comment by venven-de** [comment]
> To whoever fixes this: You would need to investigate this carefully, running through the tutorial to see if you can reproduce the error.
> 
> @venven-de can you let us know where exactly you were in the tutorial when you got this error? Which setep, or under which heading? Thanks!

just changed this within the supposed section in my initial report.
thx for the advise

**Comment by venven-de** [comment]
Actually, since the Tutorial is not suggesting a particular parcel version anymore, I'd consider that the issue has been solved.
