### ISSUE TITLE
[Nodemon] App Crashed

### ISSUE THREAD

**Issue by Davenof** [mdn/content#3953]
Please how do I fix this?

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as get] (C:\Users\User\IdeaProjects\NodeProjects\myapp\express-locallibrary-tutorial\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.(anonymous function) [as get] (C:\Users\User\IdeaProjects\NodeProjects\myapp\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:510:19)
    at Object.<anonymous> (C:\Users\User\IdeaProjects\NodeProjects\myapp\express-locallibrary-tutorial\routes\catalog.js:68:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\User\IdeaProjects\NodeProjects\myapp\express-locallibrary-tutorial\app.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by hamishwillee** [comment]
Impossible to say without your code. The best way is to check the your code in express-locallibrary-tutorial\routes\catalog.js
How does this differ from the code in https://github.com/mdn/express-locallibrary-tutorial/blob/master/routes/catalog.js

You also have an error "Route.get() requires a callback function but got a [object Undefined]". That tells you that the system cannot find the callback function. Usually that means either you have forgotten to require the appropriate controller, or that you have not provided a definition for the required controller. 

Start by looking at the specific line catalog.js:68:8 - that will tell you the missing function - now you just need to work out why it is missing - no implementation, or no implementation imported into your project

**Comment by Davenof** [comment]
I checked my codes with those here  https://github.com/mdn/express-locallibrary-tutorial/blob/master/routes/catalog.js, but didn't spot any difference. I replaced my codes with those there, same error

**Comment by Davenof** [comment]
Fixed. I missed an underscore in the book instance. Thank you.

**Comment by hamishwillee** [comment]
Easily done! Good luck.
