### ISSUE TITLE
Issue with "LocalLibrary base template": (line 7 error unexpected text "      1")

### ISSUE THREAD

**Issue by kobosh** [mdn/content#9577]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/LocalLibrary_base_template

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/LocalLibrary_base_template
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template/index.html
* Last commit: https://github.com/mdn/content/commit/a872f1455d533a205c0f7169de7d710ce646b0d7
* Document last modified: 2021-09-06T05:03:33.000Z

</details>

**Comment by kobosh** [comment]
I get error after replacing layout page. the error points to line 7 up in the head section of html ( link to import bootstrap).
the error says unexpected text( "    1).
The only place I can see the number 1 is at line 6

> Error: D:\express-locallibrary-tutorial\views\layout.pug:7:1
    5|     meta(charset='utf-8')
    6|     meta(name="viewport", content="width=device-width, initial-scale=1")
  > 7|     link(rel="stylesheet", href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", crossorigin="anonymous")
-------^
    8|     script(src="https://code.jquery.com/jquery-3.5.1.slim.min.js", integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj", crossorigin="anonymous")
    9|     script(src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js", integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV", crossorigin="anonymous")
    10|     link(rel='stylesheet', href='/stylesheets/style.css')

unexpected text "    l"
    at makeError (D:\express-locallibrary-tutorial\node_modules\pug-error\index.js:32:13)
    at Lexer.error (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:58:15)
    at Lexer.fail (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1304:10)
    at Lexer.advance (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1364:15)
    at Lexer.callLexerFunction (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.getTokens (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1375:12)
    at lex (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (D:\express-locallibrary-tutorial\node_modules\pug\lib\index.js:99:27)
    at Function.loadString [as string] (D:\express-locallibrary-tutorial\node_modules\pug-load\index.js:44:24)
    at D:\express-locallibrary-tutorial\node_modules\pug-load\index.js:31:27

**Comment by kobosh** [comment]
I removed  the links and scripts and added them back one by one.This fixed the problem!!! weired
