### ISSUE TITLE
Issue with "Create Book form": (dropDownlist error)

### ISSUE THREAD

**Issue by kobosh** [mdn/content#9677]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_book_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.html
* Last commit: https://github.com/mdn/content/commit/a872f1455d533a205c0f7169de7d710ce646b0d7
* Document last modified: 2021-09-06T05:03:33.000Z

</details>

```
D:\express-locallibrary-tutorial\views\book_form.pug:14:1 12| select#author.form-control(type='select', placeholder='Select author' name='author' required='true' ) 13| -authors.sort(function(a, b) {let textA = a.family_name.toUpperCase(); let textB = b.family_name.toUpperCase(); return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;}); > 14|         for author in authors --------^ 15| if book 16| option(value=author._id selected=(author._id.toString()===book.author._id.toString() ? 'selected' : false) ) #{author.name} 17| else unexpected text "     "
Error: D:\express-locallibrary-tutorial\views\book_form.pug:14:1
    12|       select#author.form-control(type='select', placeholder='Select author' name='author' required='true' )
    13|         -authors.sort(function(a, b) {let textA = a.family_name.toUpperCase(); let textB = b.family_name.toUpperCase(); return (textA < textB) ? -1 : (textA > textB) ? 1 : 0;});
  > 14|         for author in authors
--------^
    15|           if book
    16|             option(value=author._id selected=(author._id.toString()===book.author._id.toString() ? 'selected' : false) ) #{author.name}
    17|           else

unexpected text "     "
    at makeError (D:\express-locallibrary-tutorial\node_modules\pug-error\index.js:32:13)
    at Lexer.error (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:58:15)
    at Lexer.fail (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1304:10)
    at Lexer.advance (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1364:15)
    at Lexer.callLexerFunction (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.getTokens (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:1375:12)
    at lex (D:\express-locallibrary-tutorial\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (D:\express-locallibrary-tutorial\node_modules\pug\lib\index.js:99:27)
    at Function.loadString [as string] (D:\express-locallibrary-tutorial\node_modules\pug-load\index.js:44:24)
    at compileBody (D:\express-locallibrary-tutorial\node_modules\pug\lib\index.js:86:18)
```

**Comment by hamishwillee** [comment]
The template code works - I tested it many times, so this is most likely a bug in your code.

Given that it is saying that you have `null` at this point, probably the bug is in the controller code rather than the template itself: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form#controller%E2%80%94post_route - you're passing in a null object for some reason. 

You will have to debug this by looking at what you're passing in. YOu might also compare your project to the demo project: https://github.com/mdn/express-locallibrary-tutorial
